// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.6
// source: auth/retrieveSuccess.proto

package auth_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRetrieveSuccessItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyId string `protobuf:"bytes,1,opt,name=keyId,proto3" json:"keyId,omitempty"`
}

func (x *StreamRetrieveSuccessItemsRequest) Reset() {
	*x = StreamRetrieveSuccessItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_retrieveSuccess_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamRetrieveSuccessItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRetrieveSuccessItemsRequest) ProtoMessage() {}

func (x *StreamRetrieveSuccessItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_retrieveSuccess_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRetrieveSuccessItemsRequest.ProtoReflect.Descriptor instead.
func (*StreamRetrieveSuccessItemsRequest) Descriptor() ([]byte, []int) {
	return file_auth_retrieveSuccess_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRetrieveSuccessItemsRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type StreamRetrieveSuccessItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessItems []*StreamRetrieveSuccessItemsResponse_SuccessItem `protobuf:"bytes,1,rep,name=successItems,proto3" json:"successItems,omitempty"`
}

func (x *StreamRetrieveSuccessItemsResponse) Reset() {
	*x = StreamRetrieveSuccessItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_retrieveSuccess_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamRetrieveSuccessItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRetrieveSuccessItemsResponse) ProtoMessage() {}

func (x *StreamRetrieveSuccessItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_retrieveSuccess_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRetrieveSuccessItemsResponse.ProtoReflect.Descriptor instead.
func (*StreamRetrieveSuccessItemsResponse) Descriptor() ([]byte, []int) {
	return file_auth_retrieveSuccess_proto_rawDescGZIP(), []int{1}
}

func (x *StreamRetrieveSuccessItemsResponse) GetSuccessItems() []*StreamRetrieveSuccessItemsResponse_SuccessItem {
	if x != nil {
		return x.SuccessItems
	}
	return nil
}

type StreamRetrieveSuccessItemsResponse_SuccessItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category    string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Region      string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	ProductSku  string `protobuf:"bytes,3,opt,name=productSku,proto3" json:"productSku,omitempty"`
	ProductName string `protobuf:"bytes,4,opt,name=productName,proto3" json:"productName,omitempty"`
	OrderNumber string `protobuf:"bytes,5,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	Email       string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Size        string `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`
	Timestamp   string `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RedirectUrl string `protobuf:"bytes,9,opt,name=redirectUrl,proto3" json:"redirectUrl,omitempty"`
	ImageUrl    string `protobuf:"bytes,10,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
}

func (x *StreamRetrieveSuccessItemsResponse_SuccessItem) Reset() {
	*x = StreamRetrieveSuccessItemsResponse_SuccessItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_retrieveSuccess_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamRetrieveSuccessItemsResponse_SuccessItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRetrieveSuccessItemsResponse_SuccessItem) ProtoMessage() {}

func (x *StreamRetrieveSuccessItemsResponse_SuccessItem) ProtoReflect() protoreflect.Message {
	mi := &file_auth_retrieveSuccess_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRetrieveSuccessItemsResponse_SuccessItem.ProtoReflect.Descriptor instead.
func (*StreamRetrieveSuccessItemsResponse_SuccessItem) Descriptor() ([]byte, []int) {
	return file_auth_retrieveSuccess_proto_rawDescGZIP(), []int{1, 0}
}

func (x *StreamRetrieveSuccessItemsResponse_SuccessItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *StreamRetrieveSuccessItemsResponse_SuccessItem) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *StreamRetrieveSuccessItemsResponse_SuccessItem) GetProductSku() string {
	if x != nil {
		return x.ProductSku
	}
	return ""
}

func (x *StreamRetrieveSuccessItemsResponse_SuccessItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *StreamRetrieveSuccessItemsResponse_SuccessItem) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *StreamRetrieveSuccessItemsResponse_SuccessItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StreamRetrieveSuccessItemsResponse_SuccessItem) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *StreamRetrieveSuccessItemsResponse_SuccessItem) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *StreamRetrieveSuccessItemsResponse_SuccessItem) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *StreamRetrieveSuccessItemsResponse_SuccessItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_auth_retrieveSuccess_proto protoreflect.FileDescriptor

var file_auth_retrieveSuccess_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x39, 0x0a, 0x21, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6b,
	0x65, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49,
	0x64, 0x22, 0xb0, 0x03, 0x0a, 0x22, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0c, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x38,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0c, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0xab, 0x02, 0x0a, 0x0b, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x6b, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x6b, 0x75, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x55, 0x72, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x55, 0x72, 0x6c, 0x42, 0x13, 0x5a, 0x11, 0x61, 0x75, 0x74, 0x68, 0x3b, 0x61, 0x75, 0x74,
	0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_auth_retrieveSuccess_proto_rawDescOnce sync.Once
	file_auth_retrieveSuccess_proto_rawDescData = file_auth_retrieveSuccess_proto_rawDesc
)

func file_auth_retrieveSuccess_proto_rawDescGZIP() []byte {
	file_auth_retrieveSuccess_proto_rawDescOnce.Do(func() {
		file_auth_retrieveSuccess_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_retrieveSuccess_proto_rawDescData)
	})
	return file_auth_retrieveSuccess_proto_rawDescData
}

var file_auth_retrieveSuccess_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auth_retrieveSuccess_proto_goTypes = []interface{}{
	(*StreamRetrieveSuccessItemsRequest)(nil),              // 0: protobuf.StreamRetrieveSuccessItemsRequest
	(*StreamRetrieveSuccessItemsResponse)(nil),             // 1: protobuf.StreamRetrieveSuccessItemsResponse
	(*StreamRetrieveSuccessItemsResponse_SuccessItem)(nil), // 2: protobuf.StreamRetrieveSuccessItemsResponse.SuccessItem
}
var file_auth_retrieveSuccess_proto_depIdxs = []int32{
	2, // 0: protobuf.StreamRetrieveSuccessItemsResponse.successItems:type_name -> protobuf.StreamRetrieveSuccessItemsResponse.SuccessItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_retrieveSuccess_proto_init() }
func file_auth_retrieveSuccess_proto_init() {
	if File_auth_retrieveSuccess_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_retrieveSuccess_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamRetrieveSuccessItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_retrieveSuccess_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamRetrieveSuccessItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_retrieveSuccess_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamRetrieveSuccessItemsResponse_SuccessItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_retrieveSuccess_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_retrieveSuccess_proto_goTypes,
		DependencyIndexes: file_auth_retrieveSuccess_proto_depIdxs,
		MessageInfos:      file_auth_retrieveSuccess_proto_msgTypes,
	}.Build()
	File_auth_retrieveSuccess_proto = out.File
	file_auth_retrieveSuccess_proto_rawDesc = nil
	file_auth_retrieveSuccess_proto_goTypes = nil
	file_auth_retrieveSuccess_proto_depIdxs = nil
}
