// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.6
// source: auth/service.proto

package auth_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_service_proto protoreflect.FileDescriptor

var file_auth_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x11,
	0x61, 0x75, 0x74, 0x68, 0x2f, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x18, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x61, 0x75,
	0x74, 0x68, 0x2f, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0xd6, 0x04, 0x0a, 0x06, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x47, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x59, 0x0a, 0x0a,
	0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x65, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x50, 0x0a, 0x07, 0x50, 0x6f, 0x6c, 0x6c, 0x69,
	0x6e, 0x67, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x50, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x50, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x66, 0x0a, 0x11, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x24,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x7a, 0x0a, 0x15, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x12, 0x2c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x72, 0x0a,
	0x0f, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x13, 0x5a, 0x11, 0x61, 0x75, 0x74, 0x68, 0x3b, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_auth_service_proto_goTypes = []interface{}{
	(*StreamAuthRequest)(nil),                   // 0: protobuf.StreamAuthRequest
	(*StreamDeactivateRequest)(nil),             // 1: protobuf.StreamDeactivateRequest
	(*StreamPollingRequest)(nil),                // 2: protobuf.StreamPollingRequest
	(*StreamGetCookieDataRequest)(nil),          // 3: protobuf.StreamGetCookieDataRequest
	(*StreamHandleSuccessCheckoutRequest)(nil),  // 4: protobuf.StreamHandleSuccessCheckoutRequest
	(*StreamRetrieveSuccessItemsRequest)(nil),   // 5: protobuf.StreamRetrieveSuccessItemsRequest
	(*StreamAuthResponse)(nil),                  // 6: protobuf.StreamAuthResponse
	(*StreamDeactivateResponse)(nil),            // 7: protobuf.StreamDeactivateResponse
	(*StreamPollingResponse)(nil),               // 8: protobuf.StreamPollingResponse
	(*StreamGetCookieDataResponse)(nil),         // 9: protobuf.StreamGetCookieDataResponse
	(*StreamHandleSuccessCheckoutResponse)(nil), // 10: protobuf.StreamHandleSuccessCheckoutResponse
	(*StreamRetrieveSuccessItemsResponse)(nil),  // 11: protobuf.StreamRetrieveSuccessItemsResponse
}
var file_auth_service_proto_depIdxs = []int32{
	0,  // 0: protobuf.Stream.Auth:input_type -> protobuf.StreamAuthRequest
	1,  // 1: protobuf.Stream.Deactivate:input_type -> protobuf.StreamDeactivateRequest
	2,  // 2: protobuf.Stream.Polling:input_type -> protobuf.StreamPollingRequest
	3,  // 3: protobuf.Stream.RequestCookieData:input_type -> protobuf.StreamGetCookieDataRequest
	4,  // 4: protobuf.Stream.HandleSuccessCheckout:input_type -> protobuf.StreamHandleSuccessCheckoutRequest
	5,  // 5: protobuf.Stream.RetrieveSuccess:input_type -> protobuf.StreamRetrieveSuccessItemsRequest
	6,  // 6: protobuf.Stream.Auth:output_type -> protobuf.StreamAuthResponse
	7,  // 7: protobuf.Stream.Deactivate:output_type -> protobuf.StreamDeactivateResponse
	8,  // 8: protobuf.Stream.Polling:output_type -> protobuf.StreamPollingResponse
	9,  // 9: protobuf.Stream.RequestCookieData:output_type -> protobuf.StreamGetCookieDataResponse
	10, // 10: protobuf.Stream.HandleSuccessCheckout:output_type -> protobuf.StreamHandleSuccessCheckoutResponse
	11, // 11: protobuf.Stream.RetrieveSuccess:output_type -> protobuf.StreamRetrieveSuccessItemsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_auth_service_proto_init() }
func file_auth_service_proto_init() {
	if File_auth_service_proto != nil {
		return
	}
	file_auth_cookie_proto_init()
	file_auth_auth_proto_init()
	file_auth_handleSuccess_proto_init()
	file_auth_retrieveSuccess_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_service_proto_goTypes,
		DependencyIndexes: file_auth_service_proto_depIdxs,
	}.Build()
	File_auth_service_proto = out.File
	file_auth_service_proto_rawDesc = nil
	file_auth_service_proto_goTypes = nil
	file_auth_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StreamClient is the client API for Stream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamClient interface {
	Auth(ctx context.Context, opts ...grpc.CallOption) (Stream_AuthClient, error)
	Deactivate(ctx context.Context, opts ...grpc.CallOption) (Stream_DeactivateClient, error)
	Polling(ctx context.Context, opts ...grpc.CallOption) (Stream_PollingClient, error)
	RequestCookieData(ctx context.Context, opts ...grpc.CallOption) (Stream_RequestCookieDataClient, error)
	HandleSuccessCheckout(ctx context.Context, opts ...grpc.CallOption) (Stream_HandleSuccessCheckoutClient, error)
	RetrieveSuccess(ctx context.Context, opts ...grpc.CallOption) (Stream_RetrieveSuccessClient, error)
}

type streamClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamClient(cc grpc.ClientConnInterface) StreamClient {
	return &streamClient{cc}
}

func (c *streamClient) Auth(ctx context.Context, opts ...grpc.CallOption) (Stream_AuthClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Stream_serviceDesc.Streams[0], "/protobuf.Stream/Auth", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamAuthClient{stream}
	return x, nil
}

type Stream_AuthClient interface {
	Send(*StreamAuthRequest) error
	Recv() (*StreamAuthResponse, error)
	grpc.ClientStream
}

type streamAuthClient struct {
	grpc.ClientStream
}

func (x *streamAuthClient) Send(m *StreamAuthRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamAuthClient) Recv() (*StreamAuthResponse, error) {
	m := new(StreamAuthResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamClient) Deactivate(ctx context.Context, opts ...grpc.CallOption) (Stream_DeactivateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Stream_serviceDesc.Streams[1], "/protobuf.Stream/Deactivate", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamDeactivateClient{stream}
	return x, nil
}

type Stream_DeactivateClient interface {
	Send(*StreamDeactivateRequest) error
	Recv() (*StreamDeactivateResponse, error)
	grpc.ClientStream
}

type streamDeactivateClient struct {
	grpc.ClientStream
}

func (x *streamDeactivateClient) Send(m *StreamDeactivateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamDeactivateClient) Recv() (*StreamDeactivateResponse, error) {
	m := new(StreamDeactivateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamClient) Polling(ctx context.Context, opts ...grpc.CallOption) (Stream_PollingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Stream_serviceDesc.Streams[2], "/protobuf.Stream/Polling", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamPollingClient{stream}
	return x, nil
}

type Stream_PollingClient interface {
	Send(*StreamPollingRequest) error
	Recv() (*StreamPollingResponse, error)
	grpc.ClientStream
}

type streamPollingClient struct {
	grpc.ClientStream
}

func (x *streamPollingClient) Send(m *StreamPollingRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamPollingClient) Recv() (*StreamPollingResponse, error) {
	m := new(StreamPollingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamClient) RequestCookieData(ctx context.Context, opts ...grpc.CallOption) (Stream_RequestCookieDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Stream_serviceDesc.Streams[3], "/protobuf.Stream/RequestCookieData", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamRequestCookieDataClient{stream}
	return x, nil
}

type Stream_RequestCookieDataClient interface {
	Send(*StreamGetCookieDataRequest) error
	Recv() (*StreamGetCookieDataResponse, error)
	grpc.ClientStream
}

type streamRequestCookieDataClient struct {
	grpc.ClientStream
}

func (x *streamRequestCookieDataClient) Send(m *StreamGetCookieDataRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamRequestCookieDataClient) Recv() (*StreamGetCookieDataResponse, error) {
	m := new(StreamGetCookieDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamClient) HandleSuccessCheckout(ctx context.Context, opts ...grpc.CallOption) (Stream_HandleSuccessCheckoutClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Stream_serviceDesc.Streams[4], "/protobuf.Stream/HandleSuccessCheckout", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamHandleSuccessCheckoutClient{stream}
	return x, nil
}

type Stream_HandleSuccessCheckoutClient interface {
	Send(*StreamHandleSuccessCheckoutRequest) error
	Recv() (*StreamHandleSuccessCheckoutResponse, error)
	grpc.ClientStream
}

type streamHandleSuccessCheckoutClient struct {
	grpc.ClientStream
}

func (x *streamHandleSuccessCheckoutClient) Send(m *StreamHandleSuccessCheckoutRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamHandleSuccessCheckoutClient) Recv() (*StreamHandleSuccessCheckoutResponse, error) {
	m := new(StreamHandleSuccessCheckoutResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamClient) RetrieveSuccess(ctx context.Context, opts ...grpc.CallOption) (Stream_RetrieveSuccessClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Stream_serviceDesc.Streams[5], "/protobuf.Stream/RetrieveSuccess", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamRetrieveSuccessClient{stream}
	return x, nil
}

type Stream_RetrieveSuccessClient interface {
	Send(*StreamRetrieveSuccessItemsRequest) error
	Recv() (*StreamRetrieveSuccessItemsResponse, error)
	grpc.ClientStream
}

type streamRetrieveSuccessClient struct {
	grpc.ClientStream
}

func (x *streamRetrieveSuccessClient) Send(m *StreamRetrieveSuccessItemsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamRetrieveSuccessClient) Recv() (*StreamRetrieveSuccessItemsResponse, error) {
	m := new(StreamRetrieveSuccessItemsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamServer is the server API for Stream service.
type StreamServer interface {
	Auth(Stream_AuthServer) error
	Deactivate(Stream_DeactivateServer) error
	Polling(Stream_PollingServer) error
	RequestCookieData(Stream_RequestCookieDataServer) error
	HandleSuccessCheckout(Stream_HandleSuccessCheckoutServer) error
	RetrieveSuccess(Stream_RetrieveSuccessServer) error
}

// UnimplementedStreamServer can be embedded to have forward compatible implementations.
type UnimplementedStreamServer struct {
}

func (*UnimplementedStreamServer) Auth(Stream_AuthServer) error {
	return status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedStreamServer) Deactivate(Stream_DeactivateServer) error {
	return status.Errorf(codes.Unimplemented, "method Deactivate not implemented")
}
func (*UnimplementedStreamServer) Polling(Stream_PollingServer) error {
	return status.Errorf(codes.Unimplemented, "method Polling not implemented")
}
func (*UnimplementedStreamServer) RequestCookieData(Stream_RequestCookieDataServer) error {
	return status.Errorf(codes.Unimplemented, "method RequestCookieData not implemented")
}
func (*UnimplementedStreamServer) HandleSuccessCheckout(Stream_HandleSuccessCheckoutServer) error {
	return status.Errorf(codes.Unimplemented, "method HandleSuccessCheckout not implemented")
}
func (*UnimplementedStreamServer) RetrieveSuccess(Stream_RetrieveSuccessServer) error {
	return status.Errorf(codes.Unimplemented, "method RetrieveSuccess not implemented")
}

func RegisterStreamServer(s *grpc.Server, srv StreamServer) {
	s.RegisterService(&_Stream_serviceDesc, srv)
}

func _Stream_Auth_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServer).Auth(&streamAuthServer{stream})
}

type Stream_AuthServer interface {
	Send(*StreamAuthResponse) error
	Recv() (*StreamAuthRequest, error)
	grpc.ServerStream
}

type streamAuthServer struct {
	grpc.ServerStream
}

func (x *streamAuthServer) Send(m *StreamAuthResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamAuthServer) Recv() (*StreamAuthRequest, error) {
	m := new(StreamAuthRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Stream_Deactivate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServer).Deactivate(&streamDeactivateServer{stream})
}

type Stream_DeactivateServer interface {
	Send(*StreamDeactivateResponse) error
	Recv() (*StreamDeactivateRequest, error)
	grpc.ServerStream
}

type streamDeactivateServer struct {
	grpc.ServerStream
}

func (x *streamDeactivateServer) Send(m *StreamDeactivateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamDeactivateServer) Recv() (*StreamDeactivateRequest, error) {
	m := new(StreamDeactivateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Stream_Polling_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServer).Polling(&streamPollingServer{stream})
}

type Stream_PollingServer interface {
	Send(*StreamPollingResponse) error
	Recv() (*StreamPollingRequest, error)
	grpc.ServerStream
}

type streamPollingServer struct {
	grpc.ServerStream
}

func (x *streamPollingServer) Send(m *StreamPollingResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamPollingServer) Recv() (*StreamPollingRequest, error) {
	m := new(StreamPollingRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Stream_RequestCookieData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServer).RequestCookieData(&streamRequestCookieDataServer{stream})
}

type Stream_RequestCookieDataServer interface {
	Send(*StreamGetCookieDataResponse) error
	Recv() (*StreamGetCookieDataRequest, error)
	grpc.ServerStream
}

type streamRequestCookieDataServer struct {
	grpc.ServerStream
}

func (x *streamRequestCookieDataServer) Send(m *StreamGetCookieDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamRequestCookieDataServer) Recv() (*StreamGetCookieDataRequest, error) {
	m := new(StreamGetCookieDataRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Stream_HandleSuccessCheckout_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServer).HandleSuccessCheckout(&streamHandleSuccessCheckoutServer{stream})
}

type Stream_HandleSuccessCheckoutServer interface {
	Send(*StreamHandleSuccessCheckoutResponse) error
	Recv() (*StreamHandleSuccessCheckoutRequest, error)
	grpc.ServerStream
}

type streamHandleSuccessCheckoutServer struct {
	grpc.ServerStream
}

func (x *streamHandleSuccessCheckoutServer) Send(m *StreamHandleSuccessCheckoutResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamHandleSuccessCheckoutServer) Recv() (*StreamHandleSuccessCheckoutRequest, error) {
	m := new(StreamHandleSuccessCheckoutRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Stream_RetrieveSuccess_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServer).RetrieveSuccess(&streamRetrieveSuccessServer{stream})
}

type Stream_RetrieveSuccessServer interface {
	Send(*StreamRetrieveSuccessItemsResponse) error
	Recv() (*StreamRetrieveSuccessItemsRequest, error)
	grpc.ServerStream
}

type streamRetrieveSuccessServer struct {
	grpc.ServerStream
}

func (x *streamRetrieveSuccessServer) Send(m *StreamRetrieveSuccessItemsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamRetrieveSuccessServer) Recv() (*StreamRetrieveSuccessItemsRequest, error) {
	m := new(StreamRetrieveSuccessItemsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Stream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Stream",
	HandlerType: (*StreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Auth",
			Handler:       _Stream_Auth_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Deactivate",
			Handler:       _Stream_Deactivate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Polling",
			Handler:       _Stream_Polling_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RequestCookieData",
			Handler:       _Stream_RequestCookieData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "HandleSuccessCheckout",
			Handler:       _Stream_HandleSuccessCheckout_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RetrieveSuccess",
			Handler:       _Stream_RetrieveSuccess_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "auth/service.proto",
}
